Change the ‘shopware-plugins’ pre-commit hook to check the code style only of staged files
#4

diff --git a/git-hooks/shopware-plugin/pre-commit b/git-hooks/shopware-plugin/pre-commit
--- a/git-hooks/shopware-plugin/pre-commit
+++ b/git-hooks/shopware-plugin/pre-commit
@@ -1,9 +1,7 @@
 #!/usr/bin/env bash
-# Pre-commit Git hook.
-# Runs PHP CS and ESLint on PHP files.
 #
-# If you absolutely must commit without testing,
-# use: git commit --no-verify
+# Pre-commit Git hook.
+# Runs PHP CS and ESLint on all staged PHP and JavaScript files, respectively.
 
 repo_dir=$(pwd)
 
@@ -12,76 +10,77 @@ text_red=`tput setaf 1 > /dev/null 2>&1`
 text_green=`tput setaf 2 > /dev/null 2>&1`
 text_reset=`tput sgr0 > /dev/null 2>&1`
 
-# Check the repository for an .editorconfig file
-editor_config_path="$repo_dir/.editorconfig"
-if [ ! -f $editor_config_path ]; then
-    echo "${text_red}No .editorconfig file found in the repository. Please add the config found at http://github.com/VIISON/style-guide and commit again.${text_reset}"
-    exit 1;
-fi
-
+# Include any bash environments to make sure the $PATH is loaded properly
 function source_home_file {
     file="$HOME/$1"
     echo "Sourcing $file"
     [[ -f "${file}" ]] && source "${file}" 2> /dev/null
 }
-
-# Include any bash environments to make sure the $PATH is loaded properly
 source_home_file ".bash_profile"
 source_home_file ".zshrc"
 source_home_file ".bashrc"
 source_home_file ".profile"
 
-# Check for required packages
-type phpcs >/dev/null 2>&1 || { echo >&2 "Failed to check code style, because the require package 'phpcs' is not installed."; exit 1; }
-
-# Determine package paths
-phpcs_path=($(which phpcs))
-hookPath="`dirname \"$0\"`"
-
-# Check all staged files
-filenames=($(git diff --staged --name-only HEAD))
-numberFilesChanged="${#filenames[@]}"
-errorsFound=0
-
-if [[ $numberFilesChanged > 0 ]];
-then
-    echo "$numberFilesChanged files were changed, running PHP code style check"
-    for i in "${filenames[@]}"
-    do
-        if [[ $i == *.php ]] && [ -f $i ];
-        then
-            # Run PHP code style check (ignoring warnings)
-            $phpcs_path -p --warning-severity=0 --standard=$hookPath/../../php/php-codesniffer-standard/VIISON/ $i
-            checkResult=$?
-            if [ ${checkResult} -ne 0 ];
-            then
-                # File has code style issues
-                ((errorsFound++))
-            fi
-        fi
-    done
+# Check for any staged files
+changedFiles=($(git diff --staged --name-only HEAD))
+numChangedFiles="${#changedFiles[@]}"
+if [[ $numChangedFiles == 0 ]]; then
+    echo "No code style to check."
+    exit 0
 fi
 
-if [[ ${errorsFound} == 0 ]]
-then
-    echo "${text_green}PHP code style check passed.${text_reset}"
-else
-    echo "${text_red}PHP code style errors were found. Please fix them and commit again.${text_reset}"
+codeStyleErrors=0
+
+# Run PHP code style check (ignoring warnings)
+type phpcs >/dev/null 2>&1 || {
+    echo "${text_red}Cannot run PHP code style check, because the require package 'phpcs' is not installed.${text_reset}"
+    exit 1
+}
+if [ ! -d "${repo_dir}/vendor/viison/style-guide" ]; then
+    echo "${text_red}Cannot run PHP code style check, because the 'viison/style-guide' dependency appears to not be installed. Please run 'composer install' inside $(realpath ${repo_dir}).${text_reset}"
     exit 1
 fi
+if [ ! -f "${repo_dir}/phpcs.xml" ]; then
+    echo "${text_red}Cannot run PHP code style check, because a 'phpcs.xml' was not found in $(realpath ${repo_dir}).${text_reset}"
+    exit 1
+fi
+echo -e "\nComposer package 'viison/style-guide' is installed, running PHP Code Sniffer on staged PHP files..."
+for i in "${changedFiles[@]}"; do
+    if [[ $i == *.php ]] && [ -f $i ]; then
+        $(which phpcs) --warning-severity=0 $i
+        phpcsResult=$?
+        if [ ${phpcsResult} -ne 0 ]; then
+            # File has code style issues
+            ((codeStyleErrors++))
+        fi
+    fi
+done
 
 # Check whether we should run ESLint
-if [ -f "${repo_dir}/package.json" ];
-then
-    if [ ! -d "${repo_dir}/node_modules" ]
-    then
-        echo "${text_red}package.json found, but node_modules is missing. Please run npm install inside $(realpath ${repo_dir}).${text_reset}"
+if [ -f "${repo_dir}/package.json" ]; then
+    if [ ! -d "${repo_dir}/node_modules" ]; then
+        echo "${text_red}package.json found, but node_modules is missing. Please run 'npm install' inside $(realpath ${repo_dir}).${text_reset}"
         exit 1
     fi
-    if [ -d "${repo_dir}/node_modules/viison-style-guide" ]
-    then
-        echo "NPM package viison-style-guide is installed, running ESLint..."
-        npm run -s eslint || exit 1
-        echo
+    if [ -d "${repo_dir}/node_modules/viison-style-guide" ]; then
+        echo "NPM package 'viison-style-guide' is installed, running ESLint on staged JavaScript files..."
+        for i in "${changedFiles[@]}"; do
+            if [[ $i == *.js ]] && [ -f $i ]; then
+                node $repo_dir/node_modules/eslint/bin/eslint.js --quiet $i
+                eslintResult=$?
+                if [ ${eslintResult} -ne 0 ]; then
+                    # File has code style issues
+                    ((codeStyleErrors++))
+                fi
+            fi
+        done
     fi
+fi
+
+# Evaluate code style check results
+if [[ ${codeStyleErrors} == 0 ]]; then
+    echo -e "\n${text_green}Code style check passed.${text_reset}\n"
+else
+    echo -e "${text_red}Code style errors were found. Please fix them and commit again.${text_reset}\n"
+    exit 1
 fi
