Fix pre-commit hook

diff --git a/git-hooks/shopware-plugin/pre-commit b/git-hooks/shopware-plugin/pre-commit
--- a/git-hooks/shopware-plugin/pre-commit
+++ b/git-hooks/shopware-plugin/pre-commit
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env sh
 # Pre-commit Git hook.
 # Runs PHP CS on PHP files.
 #
@@ -10,8 +10,20 @@ text_red=`tput setaf 1`
 text_green=`tput setaf 2`
 text_reset=`tput sgr0`
 
+function source_home_file {
+    file="$HOME/$1"
+    echo $file
+    [[ -f "${file}" ]] && source "${file}"
+}
+
+# Inlcude any bash environments to make sure the $PATH is loaded properly
+source_home_file ".bash_profile"
+source_home_file ".zshrc"
+source_home_file ".bashrc"
+source_home_file ".profile"
+
 # Check for required packages
-hash phpcs 2>/dev/null || { echo >&2 "Failed to check code style, because the require package 'phpcs' is not installed."; exit 1; }
+type phpcs >/dev/null 2>&1 || { echo >&2 "Failed to check code style, because the require package 'phpcs' is not installed."; exit 1; }
 
 # Determine package paths
 phpcs_path=($(which phpcs))
